teamList.txt
=> 	modified:   teamList.txt

people/dan.watson.txt, teamList.txt
=> adding dan watson

people/charles.toller.txt, teamList.txt
I have joined this course and I would like to be listed in the appropriate listings.
=> Add Charles Toller to the people directory and team list

people/ElizabethHowell.txt, teamList.txt
I would like to add my file and update to the teamList.txt to get credit for this assignment
=> Added Elizabeth.Howell.txt and edited the teamList.txt

people/brianna.king.txt, teamList.txt
added my name to the class list and created a txt file with my info ignorer to complete the assignment
=> updated files and completed assignment

people/brett.nielsen.txt, teamList.txt
Adding Brett Nielsen to the team list and creating a brett.nielsen.txt file to satisfy homework assignment requirements.
=> Added Brett Nielsen

people/Joshua.Kropf.txt, teamList.txt
=> Changed my name line, and added a text file with my info to the repo.

people/tyler.green.txt, teamList.txt
I would like to complete the assignment
=> Adding my name

people/brian.callister.txt, teamList.txt
I would like to be included because getting credit for assignments is rad!
=> I've completed the assignment.

people/cheston.gray.txt, teamList.txt
This creative comment will let you know that I've done the assignment. Accept the pull request, please.
=> Finished Assignment

people/christian.winwood.txt, teamList.txt
=> Added Name to Text

people/connor.dibble.txt, teamList.txt
I would like to be added to the class.
=> Connor Dibble

people/joshua.webster.txt, teamList.txt
I added the desired information and shared what I would like to be called
=> Git Introduction

people/jason.boyd.txt, teamList.txt
This pull request is needed to finish the Git Introduction assignment on canvas.
=> Added my text file and followed instructions for teamList.txt. 

people/brody.larsen.txt, teamList.txt
I edited the files that are required for the homework
=> Brody Larsen pull request

people/hunter.meredith.txt, teamList.txt
I'd like to get a grade for this assignment.
=> Local changes to files saved

people/phillip.linson.txt, teamList.txt
I believe I have done as instructed, so I hope my modifications will be included.
=> Git Introduction Assignment

people/katelynn.call.txt, teamList.txt
I would like my changes to be included so that I can finish this assignment.
=> Add my file and remove the x for me, Katelynn

people/cade.rasmussen.txt, teamList.txt
Here we are i made my changes and would like you to accept my pull request! thanks
=> made my textfile and modified the teamlist file.

people/krieger.parker.txt, teamList.txt
Removed x from my name and updated preferred name.
=> Added file for myself and removed x

people/sialao.mobley.txt, teamList.txt
I would like my modifications to be included in this project so that I, Sialao Mobley, can get credit for this assignment. Thank you.
=> Sialao Mobley Git Introduction assignment

people/spencer.robinson.txt, teamList.txt
I have performed the assignment according to the instructions given on Canvas, and I do not believe my changes were excessive.
=> Spencer Robinson requesting update

people/johnathan.kunz.txt, teamList.txt
=> Changed the thing

people/dylan.armstrong.txt, teamList.txt
I want these changes to be added because its homework.
=> Update personal information

people/joshua.barney.txt, teamList.txt
=> Joshua Barney

people/karsten.boettcher.txt, teamList.txt
I've updated my personal information as listed by the assignment requirements.
=> Updated personal information

people/kendra.rogers.txt, teamList.txt
=> Kendra Rogers

people/tanner.hale.txt, teamList.txt
I know you said don't make a carriage return or anything, it was an accident, I hope it doesn't affect anything too much.
=> Added my name and preferences
